# Generated by Django 4.0.1 on 2022-06-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='reason',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
