# Generated by Django 4.0.1 on 2022-06-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_alter_idea_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
